### ISSUE TITLE
edit.js作成、editコンポーネントをApp.jsに配置

### ISSUE THREAD

**Issue by niizima1203** [Shuri-Honda-1101/teamB#3]
- edit.jsファイルを作成する
- edit.jsファイルの基盤を作成（edit関数を作り、空の`<div>`を作り、エクスポート)
- 作成したファイルをコンポーネントとして、App.jsにインポート及び配置

**Comment by Shuri-Honda-1101** [comment]
App.jsにコンポーネントを作る
